### ISSUE TITLE
Clarify that here you can/should change the test code

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3401-F13/Lab_3_starter#1]
This lab is odd because there's no way to fix the memory leak without actually modifying the test code since that's where the leak is. This goes against the grain since we normally don't want people to fiddle with the test code, and it's not ever made clear in the write-up that it's OK to change the test code here.

I'm not sure how we best do this since that provides a pretty big hint, but I do think something should be done.

**Comment by kklamberty** [comment]
It seems like one option would be to provide a backstory with some context that might suggest it's possible that the tests were written by an intern or something like that. Maybe saying that both the code and tests were written by an intern and that valgrind is just now being introduced in this company? Also, can you tell me where the text presented to the students lives right now? If it does not already, can it live here on GitHub too?

**Comment by NicMcPhee** [comment]
I like the intern idea – that would work quite well, especially if we indicate that the test code might need work as well.

The write-ups are still on the wiki like before (https://wiki.umn.edu/UMMCSci/CSci3401f13/WebHome). I would seriously like to migrate them to Github, though as I think that would potentially simplify a number of things. There are some interesting questions, though, that we'd need to sort out before we do that, however, and I'd like to include you in whatever conversation develops around that idea. Maybe we should try to set up a meeting with you and @JohnMcCall and I sometime?
